'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useDiagramStore } from '@/store/useDiagramStore';
import { useSaaSModalsStore } from '@/store/useSaaSModalsStore';
import {
  X,
  Code2,
  Copy,
  Check,
  Download,
  GitPullRequest,
  RefreshCw,
  Terminal,
  ExternalLink,
} from 'lucide-react';

export function IaCSyncModal() {
  const activeModal = useSaaSModalsStore((s) => s.activeModal);
  const closeModal = useSaaSModalsStore((s) => s.closeModal);
  const diagram = useDiagramStore((s) => s.diagram);

  const [tool, setTool] = useState<'terraform' | 'pulumi' | 'opentofu'>('terraform');
  const [copied, setCopied] = useState(false);
  const [prCreated, setPrCreated] = useState(false);

  if (activeModal !== 'iac') return null;

  // Generate Terraform HCL from Diagram nodes
  const generateTerraform = () => {
    let tf = `# Auto-generated by 3D Diagram Transformer SaaS\n# System: ${diagram.name}\nterraform {\n  required_providers {\n    aws = {\n      source  = "hashicorp/aws"\n      version = "~> 5.0"\n    }\n  }\n}\n\nprovider "aws" {\n  region = "us-east-1"\n}\n\n`;

    diagram.nodes.forEach((n) => {
      const cleanName = n.name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
      if (n.type.includes('database') || n.type === 'table') {
        tf += `resource "aws_db_instance" "${cleanName}" {\n  allocated_storage    = 20\n  engine               = "postgres"\n  instance_class       = "db.t4g.micro"\n  db_name              = "${cleanName}"\n  skip_final_snapshot  = true\n  tags = {\n    Role = "${n.properties?.stereotype || 'database'}"\n  }\n}\n\n`;
      } else if (n.type.includes('cache')) {
        tf += `resource "aws_elasticache_cluster" "${cleanName}" {\n  cluster_id           = "${cleanName}"\n  engine               = "redis"\n  node_type            = "cache.t4g.micro"\n  num_cache_nodes      = 1\n}\n\n`;
      } else if (n.type.includes('gateway')) {
        tf += `resource "aws_apigatewayv2_api" "${cleanName}" {\n  name          = "${n.name}"\n  protocol_type = "HTTP"\n}\n\n`;
      } else {
        tf += `resource "aws_ecs_service" "${cleanName}" {\n  name            = "${cleanName}"\n  cluster         = "prod-cluster"\n  task_definition = "arn:aws:ecs:us-east-1:123456:${cleanName}"\n  desired_count   = 2\n}\n\n`;
      }
    });

    return tf;
  };

  const codeSnippet = generateTerraform();

  const handleCopy = () => {
    navigator.clipboard.writeText(codeSnippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([codeSnippet], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `main.${tool === 'terraform' || tool === 'opentofu' ? 'tf' : 'ts'}`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCreatePR = () => {
    setPrCreated(true);
    setTimeout(() => setPrCreated(false), 3000);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md font-mono select-none">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          className="relative w-[95vw] sm:w-[90vw] md:max-w-2xl max-h-[90vh] flex flex-col rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950 p-4 sm:p-6 shadow-2xl overflow-hidden text-slate-800 dark:text-slate-200"
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800/80 pb-4 mb-3 shrink-0">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-500 shrink-0">
                <Code2 className="h-5 w-5" />
              </div>
              <div className="truncate">
                <h3 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2 truncate">
                  <span>Sincronização Bidirecional com IaC</span>
                  <span className="rounded bg-indigo-500/10 border border-indigo-500/30 px-2 py-0.5 text-[10px] text-indigo-400 font-semibold shrink-0">
                    Terraform & Pulumi
                  </span>
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400 truncate">
                  Transforme nós 3D em código de infraestrutura como código (IaC) e abra Pull Requests automáticos
                </p>
              </div>
            </div>
            <button
              onClick={closeModal}
              className="flex items-center justify-center min-h-[44px] min-w-[44px] rounded-lg text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 hover:text-slate-800 dark:text-slate-100 transition-colors shrink-0"
              aria-label="Fechar"
            >
              <X className="h-5 w-5" />
            </button>
          </div>

          {/* Tool Switcher */}
          <div className="flex flex-wrap items-center justify-between gap-2 mb-3 shrink-0">
            <div className="flex items-center gap-1.5 sm:gap-2">
              {(['terraform', 'opentofu', 'pulumi'] as const).map((t) => (
                <button
                  key={t}
                  onClick={() => setTool(t)}
                  className={`px-3 py-1.5 min-h-[36px] rounded-lg text-xs font-bold uppercase transition-colors ${
                    tool === t
                      ? 'bg-indigo-600 text-white shadow-sm'
                      : 'bg-slate-100 dark:bg-slate-900 text-slate-600 dark:text-slate-400 hover:bg-slate-200'
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 min-h-[36px] rounded-lg border border-slate-300 dark:border-slate-800 bg-slate-100 dark:bg-slate-900 text-xs text-slate-700 dark:text-slate-300 hover:text-white"
              >
                {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
                <span>{copied ? 'Copiado' : 'Copiar'}</span>
              </button>

              <button
                onClick={handleDownload}
                className="flex items-center gap-1.5 px-3 py-1.5 min-h-[36px] rounded-lg bg-sky-600 text-white text-xs font-bold hover:bg-sky-500 transition-colors"
              >
                <Download className="h-3.5 w-3.5" />
                <span>Baixar .{tool === 'pulumi' ? 'ts' : 'tf'}</span>
              </button>
            </div>
          </div>

          {/* Code Viewer */}
          <div className="flex-1 overflow-auto rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-900 p-4 font-mono text-[11px] text-emerald-400 leading-relaxed shadow-inner">
            <pre>{codeSnippet}</pre>
          </div>

          {/* Footer with PR Button */}
          <div className="pt-3 border-t border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-2 mt-3 shrink-0">
            <span className="text-xs text-slate-400">
              Repositório: <strong className="text-slate-200">github.com/org/infra-prod</strong>
            </span>

            <button
              onClick={handleCreatePR}
              className="flex items-center justify-center gap-2 px-4 py-2 min-h-[44px] rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold transition-all shadow-md w-full sm:w-auto"
            >
              {prCreated ? (
                <>
                  <Check className="h-3.5 w-3.5 text-emerald-300" />
                  <span>Pull Request #108 Aberto no GitHub!</span>
                </>
              ) : (
                <>
                  <GitPullRequest className="h-3.5 w-3.5" />
                  <span>Criar Pull Request com Infra 3D</span>
                </>
              )}
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
