export type DiagramType = 
  | 'microservices'
  | 'uml'
  | 'component'
  | 'infrastructure'
  | 'hardware'
  | 'ecommerce'
  | 'database'
  | 'ai-rag'
  | 'data-engineering'
  | 'iot'
  | 'bpmn'
  | 'custom';

export type NodeType =
  // Clients & Actors (Tier 5)
  | 'user'
  | 'actor'
  | 'secondary-actor'
  | 'client'
  | 'laptop'
  | 'desktop'
  | 'mobile'
  | 'device'
  | 'credit-card'
  | 'wallet'
  | 'prompt'
  | 'bi-dashboard'
  | 'monitoring-dashboard'
  | 'team'
  | 'employee'
  | 'manager'
  | 'customer'
  | 'stakeholder'
  | 'product'
  | 'temperature-sensor'
  | 'humidity-sensor'
  | 'motion-sensor'
  | 'camera-sensor'
  | 'gps'
  | 'actuator'
  | 'motor'
  | 'relay'
  | 'pump'
  | 'led'
  | 'microcontroller'
  | 'esp32'
  | 'arduino'
  | 'raspberry-pi'
  | 'iot-device'
  | 'mfa'

  // Perimeter & Networking (Tier 4)
  | 'cloud'
  | 'cloud-region'
  | 'router'
  | 'switch'
  | 'network-hub'
  | 'modem'
  | 'access-point'
  | 'gateway'
  | 'proxy'
  | 'reverse-proxy'
  | 'nat'
  | 'vpn'
  | 'subnet'
  | 'vlan'
  | 'vpc'
  | 'lan'
  | 'wan'
  | 'internet'
  | 'firewall'
  | 'waf'
  | 'ids'
  | 'ips'
  | 'honeypot'
  | 'threat'
  | 'load-balancer'
  | 'k8s-ingress'
  | 'model-gateway'
  | 'external-system'
  | 'supplier'
  | 'partner'
  | 'data-source'
  | 'plc'
  | 'patch-panel'
  | 'fiber-panel'
  | 'communication-path'
  | 'bpmn-participant'

  // Compute & Logic (Tier 3)
  | 'server'
  | 'server-rack'
  | 'blade-server'
  | 'server-room'
  | 'data-center'
  | 'availability-zone'
  | 'api'
  | 'service'
  | 'microservice'
  | 'container'
  | 'docker'
  | 'docker-image'
  | 'kubernetes'
  | 'k8s-cluster'
  | 'k8s-pod'
  | 'k8s-service'
  | 'virtual-machine'
  | 'execution-environment'
  | 'serverless-function'
  | 'authentication'
  | 'payment'
  | 'external-service'
  | 'dns-server'
  | 'dhcp-server'
  | 'siem'
  | 'soc'
  | 'identity-provider'
  | 'iam'
  | 'certificate-authority'
  | 'encryption-service'
  | 'secret-vault'
  | 'secret-manager'
  | 'cloud-monitoring'
  | 'vulnerability'
  | 'security-policy'
  | 'build'
  | 'test'
  | 'deployment'
  | 'deployment-node'
  | 'terraform'
  | 'production'
  | 'staging'
  | 'development'
  | 'producer'
  | 'consumer'
  | 'worker'
  | 'service-registry'
  | 'config-server'
  | 'monitoring'
  | 'metrics'
  | 'apm'
  | 'alert'
  | 'health-check'
  | 'incident'
  | 'sla'
  | 'slo'
  | 'organization'
  | 'company'
  | 'department'
  | 'business-process'
  | 'business-subprocess'
  | 'business-task'
  | 'business-service'
  | 'goal'
  | 'kpi'
  | 'requirement'
  | 'contract'
  | 'approval'
  | 'business-decision'
  | 'risk'
  | 'policy'
  | 'bank'
  | 'invoice'
  | 'investment'
  | 'budget'
  | 'cost-center'
  | 'data-processor'
  | 'analytics'
  | 'llm'
  | 'ai-agent'
  | 'ml-model'
  | 'neural-network'
  | 'training'
  | 'inference'
  | 'gpu-cluster'
  | 'ai-tool'
  | 'fine-tuning'
  | 'embedded-system'
  | 'cpu'
  | 'gpu'
  | 'ram'
  | 'ups'
  | 'power-supply'
  | 'cooling-system'
  | 'network-rack'
  | 'git-branch'
  | 'git-commit'
  | 'pull-request'
  // UML
  | 'uml-class'
  | 'uml-abstract-class'
  | 'uml-interface'
  | 'uml-enum'
  | 'uml-datatype'
  | 'uml-primitive'
  | 'uml-generic'
  | 'uml-template'
  | 'uml-object'
  | 'uml-component'
  | 'uml-controller'
  | 'executable'
  | 'controller'
  | 'security-module'
  | 'provided-interface'
  | 'required-interface'
  | 'component-port'
  | 'component-connector'
  | 'subsystem'
  | 'system'
  | 'software-library'
  | 'sdk'
  | 'framework'
  | 'plugin'
  | 'module'
  | 'package'
  | 'namespace'
  | 'use-case'
  | 'system-boundary'
  | 'lifeline'
  | 'sequence-object'
  | 'activation'
  | 'sequence-fragment'
  | 'action'
  | 'activity'
  | 'decision'
  | 'merge'
  | 'object-node'
  | 'activity-partition'
  | 'state'
  | 'composite-state'
  | 'substate'
  | 'guard'
  | 'entry-action'
  | 'exit-action'
  | 'state-choice'
  | 'state-junction'
  // BPMN
  | 'bpmn-start'
  | 'bpmn-end'
  | 'bpmn-intermediate-event'
  | 'bpmn-timer-event'
  | 'bpmn-error-event'
  | 'bpmn-conditional-event'
  | 'bpmn-escalation-event'
  | 'bpmn-compensation-event'
  | 'bpmn-task'
  | 'bpmn-service-task'
  | 'bpmn-script-task'
  | 'bpmn-business-rule-task'
  | 'bpmn-call-activity'
  | 'bpmn-subprocess'
  | 'bpmn-transaction'
  | 'bpmn-exclusive-gateway'
  | 'bpmn-inclusive-gateway'
  | 'bpmn-complex-gateway'
  | 'bpmn-pool'
  | 'bpmn-lane'

  // State & Transport (Tier 2)
  | 'queue'
  | 'kafka'
  | 'rabbitmq'
  | 'cache'
  | 'message-broker'
  | 'event-bus'
  | 'event-stream'
  | 'pubsub'
  | 'circuit-breaker'
  | 'distributed-lock'
  | 'etl'
  | 'elt'
  | 'data-pipeline'
  | 'data-stream'
  | 'ai-pipeline'
  | 'rag'
  | 'ci'
  | 'cd'
  | 'sync-message'
  | 'async-message'
  | 'return-message'
  | 'create-message'
  | 'destroy-message'
  | 'self-message'
  | 'loop'
  | 'parallel'
  | 'fork'
  | 'join'
  | 'control-flow'
  | 'object-flow'
  | 'signal'
  | 'state-transition'
  | 'state-event'
  | 'bpmn-message-event'
  | 'bpmn-signal-event'
  | 'bpmn-send-task'
  | 'bpmn-receive-task'
  | 'bpmn-parallel-gateway'
  | 'bpmn-event-gateway'
  | 'bpmn-sequence-flow'
  | 'bpmn-message-flow'
  | 'fiber-link'
  | 'network-cable'
  | 'tracing'
  | 'transaction'
  | 'revenue'
  | 'expense'

  // Persistence & Foundation (Tier 1)
  | 'database'
  | 'storage'
  | 'database-schema'
  | 'table'
  | 'database-view'
  | 'materialized-view'
  | 'column'
  | 'primary-key'
  | 'foreign-key'
  | 'unique-key'
  | 'database-index'
  | 'constraint'
  | 'trigger'
  | 'stored-procedure'
  | 'database-function'
  | 'database-sequence'
  | 'entity'
  | 'weak-entity'
  | 'junction-table'
  | 'database-relation'
  | 'object-storage'
  | 'block-storage'
  | 'managed-database'
  | 'cdn'
  | 'git-repository'
  | 'artifact-registry'
  | 'logs'
  | 'bank-account'
  | 'asset'
  | 'data-warehouse'
  | 'data-lake'
  | 'data-lakehouse'
  | 'data-catalog'
  | 'data-mart'
  | 'dataset'
  | 'vector-database'
  | 'embedding'
  | 'agent-memory'
  | 'ssd'
  | 'hdd'
  | 'nas'
  | 'san'
  | 'generic';

export type EdgeType =
  | 'association'
  | 'dependency'
  | 'inheritance'
  | 'composition'
  | 'aggregation'
  | 'data-flow'
  | 'network-flow'
  | 'api-request'
  | 'api-response'
  | 'message-flow'
  | 'event-flow'
  | 'sequence-flow'
  | 'bpmn-sequence-flow'
  | 'bpmn-message-flow'
  | 'deployment-flow'
  | 'authentication-flow'
  | 'encrypted-flow'
  | 'service-dependency'
  | 'replication-flow'
  | 'sync-flow'
  | 'error-flow'
  | 'monitoring-flow'
  | 'sync'
  | 'async'
  | 'event'
  | 'query'
  | 'grpc'
  | 'http'
  | 'use'
  | 'realization'
  | 'wireless'
  | 'control-flow';

export type NodeStatus =
  | 'idle'
  | 'active'
  | 'warning'
  | 'error'
  | 'offline'
  | 'loading'
  | 'selected';

export type ViewMode = '3d' | '2d' | 'split' | 'editor';

export type CameraPreset = 'overview' | 'focus' | 'orbit' | 'cinematic' | 'topology';

export interface Position3D {
  x: number;
  y: number;
  z: number;
}

export interface Position2D {
  x: number;
  y: number;
}

export interface NodeMetrics {
  cpu?: number;
  memory?: number;
  latency?: number;
  requestsPerSec?: number;
  errorRate?: number;
  statusText?: string;
  replicas?: number;
}

export interface DiagramNode {
  id: string;
  name: string;
  type: NodeType;
  layer?: 'infrastructure' | 'software' | 'database' | 'user' | 'network';
  description?: string;
  status: NodeStatus;
  importance?: number;
  metrics?: NodeMetrics;
  properties?: Record<string, string | number | boolean>;
  position2D: Position2D;
  position3D?: Position3D;
  scale?: number;
}

export interface DiagramConnection {
  id: string;
  source: string;
  target: string;
  type?: EdgeType;
  label?: string;
  description?: string;
  protocol?: string;
  style?: 'solid' | 'dashed' | 'dotted';
  trafficRate?: number;
  status?: 'healthy' | 'congested' | 'error';
  bidirectional?: boolean;
  multiplicitySource?: string;
  multiplicityTarget?: string;
}

export interface Diagram {
  id: string;
  name: string;
  type: DiagramType;
  description: string;
  nodes: DiagramNode[];
  connections: DiagramConnection[];
  createdAt: string;
  updatedAt: string;
  metadata?: {
    author?: string;
    version?: string;
    environment?: string;
  };
}

export interface LayerState {
  infrastructure: boolean;
  software: boolean;
  database: boolean;
  user: boolean;
  network: boolean;
  particles: boolean;
  grid: boolean;
  labels: boolean;
  connections: boolean;
}
