import { NodeType, NodeStatus } from '@/types/diagram';
import { NodeVisualMap, StatusVisualMap, VisualConfig } from '@/types/visual';

export const NODE_VISUALS: NodeVisualMap = {
  user: {
    color: '#38BDF8', // Cyan
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.4,
    iconName: 'User',
    badgeLabel: 'CLIENT ACTOR',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.6,
  },
  client: {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.4,
    iconName: 'Laptop',
    badgeLabel: 'CLIENT TERMINAL',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  laptop: {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.5,
    iconName: 'Laptop',
    badgeLabel: 'WORKSTATION',
    defaultScale: 1.0,
    roughness: 0.2,
    metalness: 0.8,
  },
  desktop: {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.4,
    iconName: 'Monitor',
    badgeLabel: 'DESKTOP CAD',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  mobile: {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.4,
    iconName: 'Smartphone',
    badgeLabel: 'MOBILE CLIENT',
    defaultScale: 0.9,
    roughness: 0.2,
    metalness: 0.9,
  },
  server: {
    color: '#10B981', // Emerald
    glowColor: '#059669',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.6,
    iconName: 'Server',
    badgeLabel: 'COMPUTE BLADE',
    defaultScale: 1.2,
    roughness: 0.4,
    metalness: 0.8,
  },
  database: {
    color: '#F59E0B', // Amber
    glowColor: '#D97706',
    wireframeColor: '#FCD34D',
    emissiveIntensity: 0.7,
    iconName: 'Database',
    badgeLabel: 'STORAGE REPOSITORY',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  api: {
    color: '#8B5CF6', // Violet
    glowColor: '#7C3AED',
    wireframeColor: '#C4B5FD',
    emissiveIntensity: 0.6,
    iconName: 'Network',
    badgeLabel: 'API ENDPOINT',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  service: {
    color: '#6366F1', // Indigo
    glowColor: '#4F46E5',
    wireframeColor: '#A5B4FC',
    emissiveIntensity: 0.5,
    iconName: 'Cpu',
    badgeLabel: 'CORE SERVICE',
    defaultScale: 1.05,
    roughness: 0.4,
    metalness: 0.6,
  },
  microservice: {
    color: '#06B6D4', // Cyan-teal
    glowColor: '#0891B2',
    wireframeColor: '#67E8F9',
    emissiveIntensity: 0.6,
    iconName: 'Layers',
    badgeLabel: 'MICROSERVICE POD',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  router: {
    color: '#EC4899', // Pink
    glowColor: '#DB2777',
    wireframeColor: '#F472B6',
    emissiveIntensity: 0.5,
    iconName: 'Radio',
    badgeLabel: 'NETWORK ROUTER',
    defaultScale: 1.1,
    roughness: 0.4,
    metalness: 0.7,
  },
  switch: {
    color: '#EC4899',
    glowColor: '#DB2777',
    wireframeColor: '#F472B6',
    emissiveIntensity: 0.5,
    iconName: 'Network',
    badgeLabel: 'L3 SWITCH',
    defaultScale: 1.05,
    roughness: 0.4,
    metalness: 0.7,
  },
  firewall: {
    color: '#EF4444', // Red
    glowColor: '#DC2626',
    wireframeColor: '#FCA5A5',
    emissiveIntensity: 0.7,
    iconName: 'ShieldAlert',
    badgeLabel: 'SECURITY GATEWAY',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.8,
  },
  cloud: {
    color: '#60A5FA', // Blue
    glowColor: '#3B82F6',
    wireframeColor: '#93C5FD',
    emissiveIntensity: 0.5,
    iconName: 'Cloud',
    badgeLabel: 'CLOUD REGION',
    defaultScale: 1.3,
    roughness: 0.2,
    metalness: 0.4,
  },
  storage: {
    color: '#F97316', // Orange
    glowColor: '#EA580C',
    wireframeColor: '#FDBA74',
    emissiveIntensity: 0.6,
    iconName: 'HardDrive',
    badgeLabel: 'SAN CLUSTER',
    defaultScale: 1.1,
    roughness: 0.4,
    metalness: 0.8,
  },
  container: {
    color: '#14B8A6', // Teal
    glowColor: '#0D9488',
    wireframeColor: '#5EEAD4',
    emissiveIntensity: 0.6,
    iconName: 'Box',
    badgeLabel: 'DOCKER CONTAINER',
    defaultScale: 0.95,
    roughness: 0.3,
    metalness: 0.7,
  },
  kubernetes: {
    color: '#3B82F6', // Blue
    glowColor: '#2563EB',
    wireframeColor: '#93C5FD',
    emissiveIntensity: 0.6,
    iconName: 'Compass',
    badgeLabel: 'K8S ORCHESTRATOR',
    defaultScale: 1.25,
    roughness: 0.3,
    metalness: 0.7,
  },
  'load-balancer': {
    color: '#A855F7', // Purple
    glowColor: '#9333EA',
    wireframeColor: '#D8B4FE',
    emissiveIntensity: 0.6,
    iconName: 'GitFork',
    badgeLabel: 'TRAFFIC DISTRIBUTOR',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.8,
  },
  queue: {
    color: '#EAB308', // Yellow
    glowColor: '#CA8A04',
    wireframeColor: '#FDE047',
    emissiveIntensity: 0.6,
    iconName: 'AlignJustify',
    badgeLabel: 'MESSAGE QUEUE',
    defaultScale: 1.05,
    roughness: 0.4,
    metalness: 0.6,
  },
  cache: {
    color: '#F43F5E', // Rose
    glowColor: '#E11D48',
    wireframeColor: '#FDA4AF',
    emissiveIntensity: 0.7,
    iconName: 'Zap',
    badgeLabel: 'IN-MEMORY CACHE',
    defaultScale: 1.0,
    roughness: 0.2,
    metalness: 0.7,
  },
  gateway: {
    color: '#8B5CF6',
    glowColor: '#7C3AED',
    wireframeColor: '#C4B5FD',
    emissiveIntensity: 0.6,
    iconName: 'DoorOpen',
    badgeLabel: 'API GATEWAY',
    defaultScale: 1.2,
    roughness: 0.3,
    metalness: 0.8,
  },
  authentication: {
    color: '#F59E0B',
    glowColor: '#D97706',
    wireframeColor: '#FCD34D',
    emissiveIntensity: 0.6,
    iconName: 'Lock',
    badgeLabel: 'AUTH VAULT',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.9,
  },
  payment: {
    color: '#10B981',
    glowColor: '#059669',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.6,
    iconName: 'CreditCard',
    badgeLabel: 'PAYMENT GATEWAY',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.7,
  },
  'external-service': {
    color: '#64748B',
    glowColor: '#475569',
    wireframeColor: '#94A3B8',
    emissiveIntensity: 0.4,
    iconName: 'ExternalLink',
    badgeLabel: 'EXTERNAL SERVICE',
    defaultScale: 1.0,
    roughness: 0.5,
    metalness: 0.5,
  },
  // --- UML & Structural ---
  'uml-class': {
    color: '#3B82F6',
    glowColor: '#1D4ED8',
    wireframeColor: '#93C5FD',
    emissiveIntensity: 0.5,
    iconName: 'Box',
    badgeLabel: 'UML CLASS',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  'uml-abstract-class': {
    color: '#60A5FA',
    glowColor: '#2563EB',
    wireframeColor: '#BFDBFE',
    emissiveIntensity: 0.5,
    iconName: 'Box',
    badgeLabel: 'ABSTRACT CLASS',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  'uml-interface': {
    color: '#06B6D4',
    glowColor: '#0891B2',
    wireframeColor: '#67E8F9',
    emissiveIntensity: 0.6,
    iconName: 'Layers',
    badgeLabel: 'INTERFACE',
    defaultScale: 1.1,
    roughness: 0.2,
    metalness: 0.8,
  },
  'uml-enum': {
    color: '#8B5CF6',
    glowColor: '#7C3AED',
    wireframeColor: '#C4B5FD',
    emissiveIntensity: 0.5,
    iconName: 'List',
    badgeLabel: 'ENUMERATION',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  'uml-object': {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.5,
    iconName: 'Box',
    badgeLabel: 'OBJECT INSTANCE',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.7,
  },
  'uml-component': {
    color: '#0EA5E9',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.5,
    iconName: 'Component',
    badgeLabel: 'COMPONENT',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  'uml-controller': {
    color: '#10B981', // Emerald
    glowColor: '#059669',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.55,
    iconName: 'Cpu',
    badgeLabel: 'CONTROLLER',
    defaultScale: 1.15,
    roughness: 0.25,
    metalness: 0.75,
  },
  controller: {
    color: '#10B981',
    glowColor: '#059669',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.55,
    iconName: 'Cpu',
    badgeLabel: 'CONTROLLER',
    defaultScale: 1.15,
    roughness: 0.25,
    metalness: 0.75,
  },
  executable: {
    color: '#F59E0B', // Amber
    glowColor: '#D97706',
    wireframeColor: '#FCD34D',
    emissiveIntensity: 0.55,
    iconName: 'Play',
    badgeLabel: 'EXECUTABLE',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  'security-module': {
    color: '#EC4899', // Rose/Pink
    glowColor: '#BE185D',
    wireframeColor: '#F472B6',
    emissiveIntensity: 0.6,
    iconName: 'Shield',
    badgeLabel: 'SECURITY / CRYPTO',
    defaultScale: 1.1,
    roughness: 0.2,
    metalness: 0.8,
  },
  package: {
    color: '#64748B',
    glowColor: '#475569',
    wireframeColor: '#94A3B8',
    emissiveIntensity: 0.4,
    iconName: 'Folder',
    badgeLabel: 'PACKAGE',
    defaultScale: 1.2,
    roughness: 0.4,
    metalness: 0.6,
  },
  actor: {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#7DD3FC',
    emissiveIntensity: 0.5,
    iconName: 'User',
    badgeLabel: 'ACTOR',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  'use-case': {
    color: '#EC4899',
    glowColor: '#DB2777',
    wireframeColor: '#F472B6',
    emissiveIntensity: 0.5,
    iconName: 'CircleDot',
    badgeLabel: 'USE CASE',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.6,
  },
  state: {
    color: '#10B981',
    glowColor: '#059669',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.5,
    iconName: 'Circle',
    badgeLabel: 'STATE',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.6,
  },
  activity: {
    color: '#F59E0B',
    glowColor: '#D97706',
    wireframeColor: '#FCD34D',
    emissiveIntensity: 0.5,
    iconName: 'PlayCircle',
    badgeLabel: 'ACTIVITY',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  decision: {
    color: '#F97316',
    glowColor: '#EA580C',
    wireframeColor: '#FDBA74',
    emissiveIntensity: 0.6,
    iconName: 'GitFork',
    badgeLabel: 'DECISION',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },

  // --- AI & Machine Learning ---
  llm: {
    color: '#A855F7',
    glowColor: '#7E22CE',
    wireframeColor: '#E9D5FF',
    emissiveIntensity: 0.75,
    iconName: 'Cpu',
    badgeLabel: 'LLM FOUNDATION',
    defaultScale: 1.3,
    roughness: 0.2,
    metalness: 0.8,
  },
  'ai-agent': {
    color: '#8B5CF6',
    glowColor: '#6D28D9',
    wireframeColor: '#DDD6FE',
    emissiveIntensity: 0.7,
    iconName: 'Bot',
    badgeLabel: 'AUTONOMOUS AGENT',
    defaultScale: 1.15,
    roughness: 0.2,
    metalness: 0.8,
  },
  'ml-model': {
    color: '#C084FC',
    glowColor: '#9333EA',
    wireframeColor: '#F3E8FF',
    emissiveIntensity: 0.65,
    iconName: 'Brain',
    badgeLabel: 'ML MODEL',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  'neural-network': {
    color: '#D946EF',
    glowColor: '#A21CAF',
    wireframeColor: '#F5D0FE',
    emissiveIntensity: 0.7,
    iconName: 'Activity',
    badgeLabel: 'NEURAL NET',
    defaultScale: 1.25,
    roughness: 0.2,
    metalness: 0.8,
  },
  inference: {
    color: '#E879F9',
    glowColor: '#C026D3',
    wireframeColor: '#FAE8FF',
    emissiveIntensity: 0.65,
    iconName: 'Zap',
    badgeLabel: 'INFERENCE ENGINE',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  'gpu-cluster': {
    color: '#10B981',
    glowColor: '#047857',
    wireframeColor: '#A7F3D0',
    emissiveIntensity: 0.7,
    iconName: 'Server',
    badgeLabel: 'GPU CLUSTER (H100)',
    defaultScale: 1.3,
    roughness: 0.3,
    metalness: 0.9,
  },
  prompt: {
    color: '#F472B6',
    glowColor: '#DB2777',
    wireframeColor: '#FBCFE8',
    emissiveIntensity: 0.55,
    iconName: 'Terminal',
    badgeLabel: 'PROMPT INPUT',
    defaultScale: 1.0,
    roughness: 0.2,
    metalness: 0.8,
  },
  'vector-database': {
    color: '#F59E0B',
    glowColor: '#B45309',
    wireframeColor: '#FDE68A',
    emissiveIntensity: 0.7,
    iconName: 'Database',
    badgeLabel: 'VECTOR DB (PINECONE)',
    defaultScale: 1.2,
    roughness: 0.2,
    metalness: 0.8,
  },
  embedding: {
    color: '#FBBF24',
    glowColor: '#D97706',
    wireframeColor: '#FEF3C7',
    emissiveIntensity: 0.6,
    iconName: 'Hash',
    badgeLabel: 'EMBEDDINGS',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.7,
  },
  rag: {
    color: '#818CF8',
    glowColor: '#4F46E5',
    wireframeColor: '#C7D2FE',
    emissiveIntensity: 0.65,
    iconName: 'Repeat',
    badgeLabel: 'RAG PIPELINE',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  'agent-memory': {
    color: '#EC4899',
    glowColor: '#BE185D',
    wireframeColor: '#FCE7F3',
    emissiveIntensity: 0.6,
    iconName: 'HardDrive',
    badgeLabel: 'AGENT MEMORY',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.8,
  },

  // --- Data Engineering & Big Data ---
  'data-lakehouse': {
    color: '#0284C7',
    glowColor: '#0369A1',
    wireframeColor: '#BAE6FD',
    emissiveIntensity: 0.7,
    iconName: 'Database',
    badgeLabel: 'DATA LAKEHOUSE',
    defaultScale: 1.3,
    roughness: 0.2,
    metalness: 0.8,
  },
  'data-lake': {
    color: '#06B6D4',
    glowColor: '#0E7490',
    wireframeColor: '#CFFAFE',
    emissiveIntensity: 0.65,
    iconName: 'Database',
    badgeLabel: 'DATA LAKE (S3)',
    defaultScale: 1.25,
    roughness: 0.2,
    metalness: 0.8,
  },
  'data-warehouse': {
    color: '#0D9488',
    glowColor: '#0F766E',
    wireframeColor: '#CCFBF1',
    emissiveIntensity: 0.7,
    iconName: 'Database',
    badgeLabel: 'SNOWFLAKE DWH',
    defaultScale: 1.25,
    roughness: 0.2,
    metalness: 0.8,
  },
  'data-source': {
    color: '#64748B',
    glowColor: '#334155',
    wireframeColor: '#CBD5E1',
    emissiveIntensity: 0.5,
    iconName: 'Database',
    badgeLabel: 'SOURCE SYSTEM',
    defaultScale: 1.1,
    roughness: 0.4,
    metalness: 0.6,
  },
  etl: {
    color: '#F59E0B',
    glowColor: '#D97706',
    wireframeColor: '#FCD34D',
    emissiveIntensity: 0.6,
    iconName: 'Workflow',
    badgeLabel: 'ETL PIPELINE',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  elt: {
    color: '#F59E0B',
    glowColor: '#D97706',
    wireframeColor: '#FCD34D',
    emissiveIntensity: 0.6,
    iconName: 'Workflow',
    badgeLabel: 'ELT ENGINE',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  'data-pipeline': {
    color: '#6366F1',
    glowColor: '#4338CA',
    wireframeColor: '#C7D2FE',
    emissiveIntensity: 0.6,
    iconName: 'GitMerge',
    badgeLabel: 'DATA PIPELINE',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  'data-stream': {
    color: '#EAB308',
    glowColor: '#A16207',
    wireframeColor: '#FEF08A',
    emissiveIntensity: 0.6,
    iconName: 'Activity',
    badgeLabel: 'STREAM INGEST',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  kafka: {
    color: '#EF4444',
    glowColor: '#B91C1C',
    wireframeColor: '#FECACA',
    emissiveIntensity: 0.65,
    iconName: 'Radio',
    badgeLabel: 'APACHE KAFKA',
    defaultScale: 1.2,
    roughness: 0.3,
    metalness: 0.8,
  },
  'bi-dashboard': {
    color: '#10B981',
    glowColor: '#059669',
    wireframeColor: '#A7F3D0',
    emissiveIntensity: 0.55,
    iconName: 'BarChart',
    badgeLabel: 'BI / POWER BI',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },

  // --- IoT, Embedded & Hardware ---
  esp32: {
    color: '#10B981',
    glowColor: '#047857',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.7,
    iconName: 'Cpu',
    badgeLabel: 'ESP32 SOC',
    defaultScale: 1.2,
    roughness: 0.25,
    metalness: 0.85,
  },
  arduino: {
    color: '#06B6D4',
    glowColor: '#0891B2',
    wireframeColor: '#67E8F9',
    emissiveIntensity: 0.7,
    iconName: 'Cpu',
    badgeLabel: 'ARDUINO UNO',
    defaultScale: 1.2,
    roughness: 0.25,
    metalness: 0.85,
  },
  'raspberry-pi': {
    color: '#EF4444',
    glowColor: '#B91C1C',
    wireframeColor: '#FCA5A5',
    emissiveIntensity: 0.7,
    iconName: 'Cpu',
    badgeLabel: 'RASPBERRY PI',
    defaultScale: 1.2,
    roughness: 0.25,
    metalness: 0.85,
  },
  'iot-device': {
    color: '#14B8A6',
    glowColor: '#0F766E',
    wireframeColor: '#5EEAD4',
    emissiveIntensity: 0.6,
    iconName: 'Radio',
    badgeLabel: 'IOT PERIPHERAL',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.75,
  },
  'temperature-sensor': {
    color: '#F43F5E',
    glowColor: '#BE123C',
    wireframeColor: '#FECDD3',
    emissiveIntensity: 0.6,
    iconName: 'Thermometer',
    badgeLabel: 'TEMP SENSOR (DS18B20)',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  'humidity-sensor': {
    color: '#38BDF8',
    glowColor: '#0284C7',
    wireframeColor: '#BAE6FD',
    emissiveIntensity: 0.6,
    iconName: 'Droplets',
    badgeLabel: 'HUMIDITY (DHT22)',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  'motion-sensor': {
    color: '#F59E0B',
    glowColor: '#B45309',
    wireframeColor: '#FDE68A',
    emissiveIntensity: 0.6,
    iconName: 'Eye',
    badgeLabel: 'PIR MOTION SENSOR',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.7,
  },
  'camera-sensor': {
    color: '#A855F7',
    glowColor: '#7E22CE',
    wireframeColor: '#E9D5FF',
    emissiveIntensity: 0.6,
    iconName: 'Camera',
    badgeLabel: 'VISION SENSOR',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.8,
  },
  actuator: {
    color: '#F97316',
    glowColor: '#C2410C',
    wireframeColor: '#FFEDD5',
    emissiveIntensity: 0.6,
    iconName: 'ToggleLeft',
    badgeLabel: 'ACTUATOR UNIT',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.8,
  },
  relay: {
    color: '#EAB308',
    glowColor: '#A16207',
    wireframeColor: '#FEF08A',
    emissiveIntensity: 0.6,
    iconName: 'Power',
    badgeLabel: 'RELAY SWITCH',
    defaultScale: 1.0,
    roughness: 0.3,
    metalness: 0.8,
  },
  motor: {
    color: '#6366F1',
    glowColor: '#4338CA',
    wireframeColor: '#C7D2FE',
    emissiveIntensity: 0.6,
    iconName: 'RotateCw',
    badgeLabel: 'SERVO MOTOR',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.8,
  },
  microcontroller: {
    color: '#10B981',
    glowColor: '#047857',
    wireframeColor: '#6EE7B7',
    emissiveIntensity: 0.7,
    iconName: 'Cpu',
    badgeLabel: 'MCU CORE',
    defaultScale: 1.15,
    roughness: 0.25,
    metalness: 0.85,
  },

  // --- BPMN & Business ---
  'bpmn-start': {
    color: '#10B981',
    glowColor: '#047857',
    wireframeColor: '#A7F3D0',
    emissiveIntensity: 0.7,
    iconName: 'Play',
    badgeLabel: 'BPMN START',
    defaultScale: 1.0,
    roughness: 0.2,
    metalness: 0.8,
  },
  'bpmn-end': {
    color: '#EF4444',
    glowColor: '#B91C1C',
    wireframeColor: '#FECACA',
    emissiveIntensity: 0.7,
    iconName: 'Square',
    badgeLabel: 'BPMN END',
    defaultScale: 1.0,
    roughness: 0.2,
    metalness: 0.8,
  },
  'bpmn-task': {
    color: '#3B82F6',
    glowColor: '#1D4ED8',
    wireframeColor: '#BFDBFE',
    emissiveIntensity: 0.55,
    iconName: 'CheckSquare',
    badgeLabel: 'USER TASK',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  'bpmn-service-task': {
    color: '#6366F1',
    glowColor: '#4338CA',
    wireframeColor: '#C7D2FE',
    emissiveIntensity: 0.6,
    iconName: 'Cpu',
    badgeLabel: 'SERVICE TASK',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  'bpmn-exclusive-gateway': {
    color: '#F59E0B',
    glowColor: '#B45309',
    wireframeColor: '#FDE68A',
    emissiveIntensity: 0.7,
    iconName: 'X',
    badgeLabel: 'XOR GATEWAY',
    defaultScale: 1.15,
    roughness: 0.2,
    metalness: 0.8,
  },
  'bpmn-parallel-gateway': {
    color: '#10B981',
    glowColor: '#047857',
    wireframeColor: '#A7F3D0',
    emissiveIntensity: 0.7,
    iconName: 'Plus',
    badgeLabel: 'AND GATEWAY',
    defaultScale: 1.15,
    roughness: 0.2,
    metalness: 0.8,
  },
  'bpmn-inclusive-gateway': {
    color: '#8B5CF6',
    glowColor: '#6D28D9',
    wireframeColor: '#DDD6FE',
    emissiveIntensity: 0.7,
    iconName: 'Circle',
    badgeLabel: 'OR GATEWAY',
    defaultScale: 1.15,
    roughness: 0.2,
    metalness: 0.8,
  },
  'bpmn-pool': {
    color: '#475569',
    glowColor: '#334155',
    wireframeColor: '#94A3B8',
    emissiveIntensity: 0.4,
    iconName: 'Layout',
    badgeLabel: 'PROCESS POOL',
    defaultScale: 1.4,
    roughness: 0.4,
    metalness: 0.5,
  },
  'bpmn-lane': {
    color: '#64748B',
    glowColor: '#475569',
    wireframeColor: '#CBD5E1',
    emissiveIntensity: 0.4,
    iconName: 'Columns',
    badgeLabel: 'LANE',
    defaultScale: 1.2,
    roughness: 0.4,
    metalness: 0.5,
  },

  // --- Security & Perimeter ---
  waf: {
    color: '#EF4444',
    glowColor: '#B91C1C',
    wireframeColor: '#FCA5A5',
    emissiveIntensity: 0.7,
    iconName: 'ShieldCheck',
    badgeLabel: 'WAF DEFENSE',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.8,
  },
  vpn: {
    color: '#8B5CF6',
    glowColor: '#6D28D9',
    wireframeColor: '#DDD6FE',
    emissiveIntensity: 0.6,
    iconName: 'Lock',
    badgeLabel: 'VPN TUNNEL',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.8,
  },
  'secret-vault': {
    color: '#F59E0B',
    glowColor: '#B45309',
    wireframeColor: '#FDE68A',
    emissiveIntensity: 0.7,
    iconName: 'Key',
    badgeLabel: 'SECRET VAULT',
    defaultScale: 1.1,
    roughness: 0.2,
    metalness: 0.9,
  },
  iam: {
    color: '#38BDF8',
    glowColor: '#0369A1',
    wireframeColor: '#BAE6FD',
    emissiveIntensity: 0.6,
    iconName: 'UserCheck',
    badgeLabel: 'IAM POLICIES',
    defaultScale: 1.05,
    roughness: 0.3,
    metalness: 0.7,
  },
  siem: {
    color: '#EC4899',
    glowColor: '#BE185D',
    wireframeColor: '#FCE7F3',
    emissiveIntensity: 0.6,
    iconName: 'Eye',
    badgeLabel: 'SIEM AUDIT',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },

  // --- Database & Entity-Relationship ---
  table: {
    color: '#3B82F6',
    glowColor: '#1D4ED8',
    wireframeColor: '#93C5FD',
    emissiveIntensity: 0.55,
    iconName: 'Table',
    badgeLabel: 'SQL TABLE',
    defaultScale: 1.15,
    roughness: 0.3,
    metalness: 0.7,
  },
  entity: {
    color: '#6366F1',
    glowColor: '#4338CA',
    wireframeColor: '#C7D2FE',
    emissiveIntensity: 0.55,
    iconName: 'Box',
    badgeLabel: 'ER ENTITY',
    defaultScale: 1.1,
    roughness: 0.3,
    metalness: 0.7,
  },
  'primary-key': {
    color: '#F59E0B',
    glowColor: '#B45309',
    wireframeColor: '#FDE68A',
    emissiveIntensity: 0.6,
    iconName: 'Key',
    badgeLabel: 'PRIMARY KEY',
    defaultScale: 0.95,
    roughness: 0.3,
    metalness: 0.8,
  },
  'foreign-key': {
    color: '#10B981',
    glowColor: '#047857',
    wireframeColor: '#A7F3D0',
    emissiveIntensity: 0.6,
    iconName: 'Link',
    badgeLabel: 'FOREIGN KEY',
    defaultScale: 0.95,
    roughness: 0.3,
    metalness: 0.8,
  },

  generic: {
    color: '#94A3B8',
    glowColor: '#64748B',
    wireframeColor: '#CBD5E1',
    emissiveIntensity: 0.4,
    iconName: 'Box',
    badgeLabel: 'LOGICAL NODE',
    defaultScale: 1.0,
    roughness: 0.4,
    metalness: 0.5,
  },
};

export function getNodeVisual(type: string): VisualConfig {
  return NODE_VISUALS[type as NodeType] || NODE_VISUALS.generic;
}


export const STATUS_VISUALS: StatusVisualMap = {
  idle: {
    color: '#64748B',
    emissive: '#475569',
    badgeBg: 'bg-slate-800/80',
    badgeText: 'text-slate-300',
    pulseSpeed: 1,
  },
  active: {
    color: '#10B981',
    emissive: '#059669',
    badgeBg: 'bg-emerald-950/80 border-emerald-500/40',
    badgeText: 'text-emerald-400',
    pulseSpeed: 2,
  },
  warning: {
    color: '#F59E0B',
    emissive: '#D97706',
    badgeBg: 'bg-amber-950/80 border-amber-500/40',
    badgeText: 'text-amber-400',
    pulseSpeed: 3,
  },
  error: {
    color: '#F43F5E',
    emissive: '#E11D48',
    badgeBg: 'bg-rose-950/80 border-rose-500/40',
    badgeText: 'text-rose-400',
    pulseSpeed: 4,
  },
  offline: {
    color: '#334155',
    emissive: '#1E293B',
    badgeBg: 'bg-slate-900/80 border-slate-700/40',
    badgeText: 'text-slate-500',
    pulseSpeed: 0,
  },
  loading: {
    color: '#8B5CF6',
    emissive: '#7C3AED',
    badgeBg: 'bg-violet-950/80 border-violet-500/40',
    badgeText: 'text-violet-400',
    pulseSpeed: 3,
  },
  selected: {
    color: '#38BDF8',
    emissive: '#0284C7',
    badgeBg: 'bg-sky-950/90 border-sky-400/60',
    badgeText: 'text-sky-300',
    pulseSpeed: 2,
  },
};
